### ISSUE TITLE
erdview화면에서 용어사전 클릭시 에러

### ISSUE THREAD

**Issue by happytk** [happytk/ercc#62]
```
Traceback (most recent call last):
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/happytk/Dev/ercc/ercc/ercc_bps/erc/views.py", line 717, in get_glossary_info
    return dumps(ercDataModel.get_glossary_Info(project_id, model_id), ensure_ascii=False)
  File "/Users/happytk/Dev/ercc/ercc/ercc_bps/erc/ercDataModel.py", line 2062, in get_glossary_Info
    glossary = Glossary.head_objects.get(id=ObjectId(glossary_id))
  File "/usr/local/Cellar/pyenv/1.0.10/versions/3.6.1/envs/ercc361/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 277, in get
    raise queryset._document.DoesNotExist(msg)
ercc.ercc_bps.glossary.models.DoesNotExist: GlossaryBase.Glossary matching query does not exist.
```

**Comment by happytk** [comment]
전사용어사전을 조회하지 못해서 나는 오류 (glossary -> glossary base)
